'use client';

import React, { useState } from 'react';
import { 
  ShieldCheck, 
  Database, 
  Zap, 
  Settings, 
  Lock, 
  FileText, 
  ArrowRight,
  HelpCircle,
  ChevronDown,
  Layout,
  RefreshCw,
  Cpu
} from 'lucide-react';

const StrategyPage = () => {
  const [activeFaq, setActiveFaq] = useState<number | null>(null);

  const sections = [
    { id: 'logic', title: 'Logic Architecture', icon: Cpu },
    { id: 'security', title: 'Data Security', icon: ShieldCheck },
    { id: 'salesforce', title: 'Salesforce Roadmap', icon: RefreshCw },
    { id: 'faq', title: 'Strategy FAQ', icon: HelpCircle },
  ];

  const faqs = [
    {
      q: "How did you build the pricing if we didn't share the Excel sheets?",
      a: "The system uses a 'Formula Injection' architecture. We used the specific constraints shared during our discovery call (e.g., 20% structural overhead, 15% labor multipliers) to build the engine's skeleton. It is currently running on 'Standardized High-Confidence' data, but it's designed to accept your proprietary Excel logic the moment we sign the NDA."
    },
    {
      q: "Is our proprietary pricing safe?",
      a: "Yes. The current system is running in a private sandbox. Once deployed, the pricing engine runs on your private environment. No third-party AI or external database has access to your margin calculations or labor rates."
    },
    {
      q: "How long does it take to update a price?",
      a: "Seconds. We've built an 'Internal Admin Console' concept where an estimator can update a base square-foot rate or a shipping multiplier, and every new proposal generated by the team will instantly reflect that change."
    },
    {
      q: "Can this handle complex multi-screen venues (e.g. Stadiums)?",
      a: "Absolutely. The backend supports 'Multi-Zone Configuration' where you can append a Scoreboard, a Ribbon Board, and a Vomitory display to a single proposal, calculating the total installation synergy and combined labor costs."
    },
    {
      q: "What about Salesforce integration?",
      a: "The system is 'API-First'. This means we have a dedicated hook waiting for Salesforce. When an Opportunity reaches 'Stage: Proposal Needed', Salesforce can ping this system, pre-fill the client data, and wait for your estimator to just pick the hardware."
    }
  ];

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans">
      {/* Navigation */}
      <nav className="sticky top-0 z-50 bg-[#003366] text-white shadow-lg">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-white p-1 rounded shadow-inner">
               <span className="text-[#003366] font-black text-xl tracking-tighter">ANC</span>
            </div>
            <span className="font-medium tracking-tight border-l border-white/20 pl-3 ml-1 hidden md:block">
              Strategy & Implementation Portal
            </span>
          </div>
          <div className="flex gap-6 overflow-x-auto whitespace-nowrap scrollbar-hide py-2">
            {sections.map((s) => (
              <a 
                key={s.id} 
                href={`#${s.id}`} 
                className="text-sm font-semibold hover:text-blue-300 transition-colors uppercase tracking-widest"
              >
                {s.title}
              </a>
            ))}
          </div>
        </div>
      </nav>

      <main className="max-w-5xl mx-auto px-4 py-12">
        {/* Hero Section */}
        <header className="mb-20 text-center">
          <div className="inline-flex items-center gap-2 bg-blue-100 text-[#003366] px-4 py-2 rounded-full text-sm font-bold mb-6">
            <Zap size={16} /> 
            PHASE 1: PROOF OF CONCEPT READY
          </div>
          <h1 className="text-5xl md:text-6xl font-black text-slate-900 mb-6 tracking-tight">
            The <span className="text-[#003366]">ANC Estimator</span> <br/>Logic Engine
          </h1>
          <p className="text-xl text-slate-600 max-w-2xl mx-auto leading-relaxed">
            Transforming multi-day manual estimations into a 5-minute automated workflow while protecting your proprietary math.
          </p>
        </header>

        {/* Logic Section */}
        <section id="logic" className="mb-24 scroll-mt-24">
          <div className="bg-white rounded-3xl p-8 md:p-12 shadow-xl shadow-slate-200 border border-slate-100">
            <div className="flex items-center gap-4 mb-8">
              <div className="bg-[#003366] p-3 rounded-2xl text-white">
                <Cpu size={32} />
              </div>
              <h2 className="text-3xl font-bold">The "Zero-Knowledge" Architecture</h2>
            </div>
            
            <div className="grid md:grid-cols-2 gap-12">
              <div>
                <p className="text-lg text-slate-700 mb-6 font-medium leading-relaxed">
                  We understood from day one: <span className="text-[#003366] font-bold">Your installation logic is your IP.</span>
                </p>
                <p className="text-slate-600 mb-6">
                  That's why we didn't build a static calculator. We built a <strong>Formula Engine</strong> that is ready to be mapped to your internal spreadsheets as soon as the NDA is finalized.
                </p>
                <ul className="space-y-4">
                  {[
                    "Standardized Logic vs. Proprietary Logic separation",
                    "Dynamic Multipliers (Wind Load, Union Labor, Interior Access)",
                    "Scenario-Based 'Fuzzy' Inference for complex installs",
                    "Dual-Output (Branded PDF + Internal Audit Excel)"
                  ].map((item, i) => (
                    <li key={i} className="flex items-start gap-3 text-slate-700 font-medium">
                      <div className="mt-1 bg-green-500 rounded-full p-1 text-white">
                        <ArrowRight size={12} />
                      </div>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="bg-slate-50 rounded-2xl p-6 border border-slate-200">
                <h3 className="font-bold text-slate-900 mb-4 uppercase text-xs tracking-widest">Pricing Waterfall Logic</h3>
                <div className="space-y-4">
                   <div className="flex justify-between items-center pb-2 border-b border-slate-200">
                      <span className="text-sm font-semibold text-slate-500">Manual Override</span>
                      <span className="bg-green-100 text-green-700 px-2 py-1 rounded text-xs font-bold uppercase tracking-tighter">100% Priority</span>
                   </div>
                   <div className="flex justify-between items-center pb-2 border-b border-slate-200">
                      <span className="text-sm font-semibold text-slate-500">ANC Master Sheet</span>
                      <span className="bg-blue-100 text-blue-700 px-2 py-1 rounded text-xs font-bold uppercase tracking-tighter">API Connected</span>
                   </div>
                   <div className="flex justify-between items-center opacity-50">
                      <span className="text-sm font-semibold text-slate-500 text-strikethrough">Public Web Data</span>
                      <span className="bg-red-100 text-red-700 px-2 py-1 rounded text-xs font-bold uppercase tracking-tighter">Never Used</span>
                   </div>
                </div>
                <div className="mt-8 p-4 bg-[#003366] rounded-xl text-white text-sm italic">
                  "The logic represents what your estimators already trust. We just gave it a brain and a professional skin."
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Security Section */}
        <section id="security" className="mb-24 scroll-mt-24">
          <div className="grid md:grid-cols-3 gap-6">
            {[
              { 
                title: "IP Protection", 
                desc: "Your formulas never leave the secure application layer. It's a black box to the AI.",
                icon: Lock
              },
              { 
                title: "Local Excellence", 
                desc: "The system creates a 'Perfect PDF' instantly, saving days of formatting manually.",
                icon: FileText
              },
              { 
                title: "Internal Audit", 
                desc: "Every proposal creates a hidden Excel file for your team to check the math.",
                icon: Layout
              }
            ].map((card, i) => (
              <div key={i} className="bg-[#003366] text-white p-8 rounded-3xl shadow-lg border-t-4 border-blue-400">
                <card.icon className="mb-4 text-blue-300" size={32} />
                <h3 className="text-xl font-bold mb-2">{card.title}</h3>
                <p className="text-blue-100 text-sm leading-relaxed">{card.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Salesforce Roadmap */}
        <section id="salesforce" className="mb-24 scroll-mt-24">
          <div className="bg-blue-50 border-2 border-blue-100 rounded-3xl p-8 md:p-12 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-8 text-blue-100 opacity-20 pointer-events-none">
              <RefreshCw size={120} />
            </div>
            <h2 className="text-3xl font-black text-[#003366] mb-8">Salesforce Integration Roadmap</h2>
            <div className="relative">
              <div className="absolute left-4 top-0 bottom-0 w-1 bg-blue-200"></div>
              <div className="space-y-12 pl-12">
                {[
                  { step: "Phase 1: Direct Entry", detail: "Estimator fills out the 5-minute wizard based on sales notes." },
                  { step: "Phase 2: One-Way Connector", detail: "Salesforce triggers the system with Client Name and Venue details." },
                  { step: "Phase 3: Automated Proposal", detail: "AI reads the Salesforce opportunity brief and auto-fills 80% of the wizard." }
                ].map((item, i) => (
                  <div key={i} className="relative">
                    <div className="absolute -left-[3.5rem] mt-1 bg-[#003366] text-white w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm shadow-lg">
                      {i + 1}
                    </div>
                    <h4 className="font-bold text-slate-900 text-lg">{item.step}</h4>
                    <p className="text-slate-600">{item.detail}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section id="faq" className="mb-24 scroll-mt-24">
          <h2 className="text-3xl font-black text-slate-900 mb-10 flex items-center gap-3">
             <HelpCircle className="text-[#003366]" size={32} /> 
             The "Pre-Meeting" FAQ
          </h2>
          <div className="space-y-4">
            {faqs.map((faq, i) => (
              <div key={i} className="bg-white border border-slate-200 rounded-2xl overflow-hidden hover:border-blue-300 transition-colors shadow-sm">
                <button 
                  onClick={() => setActiveFaq(activeFaq === i ? null : i)}
                  className="w-full text-left p-6 flex justify-between items-center"
                >
                  <span className="font-bold text-slate-800 text-lg leading-tight pr-8">{faq.q}</span>
                  <ChevronDown className={`shrink-0 text-slate-400 transition-transform ${activeFaq === i ? 'rotate-180' : ''}`} />
                </button>
                {activeFaq === i && (
                  <div className="px-6 pb-6 text-slate-600 border-t border-slate-50 pt-2 leading-relaxed animate-in fade-in duration-300">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* Footer/Handover */}
        <footer className="text-center pt-12 border-t border-slate-200">
          <p className="text-sm font-bold text-slate-400 uppercase tracking-[.25em] mb-4">Implementation Partner</p>
          <div className="inline-block bg-[#003366] text-white px-8 py-4 rounded-2xl font-black tracking-widest text-lg">
             B A S H E E R
          </div>
          <p className="mt-8 text-slate-500 text-sm">
            © 2026 ANC Automated Proposal Initiative. All proprietary logic protected.
          </p>
        </footer>
      </main>
    </div>
  );
};

export default StrategyPage;

